# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bridge_pb2 as bridge__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bridge_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BridgeServiceStub:
    """BridgeService enables Go agent to call Python modules via IPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteModule = channel.unary_unary(
                '/x404x.v1.BridgeService/ExecuteModule',
                request_serializer=bridge__pb2.ModuleRequest.SerializeToString,
                response_deserializer=bridge__pb2.ModuleResponse.FromString,
                _registered_method=True)
        self.AIAnalyze = channel.unary_stream(
                '/x404x.v1.BridgeService/AIAnalyze',
                request_serializer=bridge__pb2.AIAnalyzeRequest.SerializeToString,
                response_deserializer=bridge__pb2.AIAnalyzeResponse.FromString,
                _registered_method=True)
        self.ReconStream = channel.unary_stream(
                '/x404x.v1.BridgeService/ReconStream',
                request_serializer=bridge__pb2.ReconRequest.SerializeToString,
                response_deserializer=bridge__pb2.ReconResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/x404x.v1.BridgeService/HealthCheck',
                request_serializer=bridge__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=bridge__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class BridgeServiceServicer:
    """BridgeService enables Go agent to call Python modules via IPC
    """

    def ExecuteModule(self, request, context):
        """Execute a Python module function
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AIAnalyze(self, request, context):
        """Stream AI analysis results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReconStream(self, request, context):
        """Stream recon results
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteModule': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteModule,
                    request_deserializer=bridge__pb2.ModuleRequest.FromString,
                    response_serializer=bridge__pb2.ModuleResponse.SerializeToString,
            ),
            'AIAnalyze': grpc.unary_stream_rpc_method_handler(
                    servicer.AIAnalyze,
                    request_deserializer=bridge__pb2.AIAnalyzeRequest.FromString,
                    response_serializer=bridge__pb2.AIAnalyzeResponse.SerializeToString,
            ),
            'ReconStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ReconStream,
                    request_deserializer=bridge__pb2.ReconRequest.FromString,
                    response_serializer=bridge__pb2.ReconResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=bridge__pb2.HealthCheckRequest.FromString,
                    response_serializer=bridge__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'x404x.v1.BridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('x404x.v1.BridgeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BridgeService:
    """BridgeService enables Go agent to call Python modules via IPC
    """

    @staticmethod
    def ExecuteModule(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x404x.v1.BridgeService/ExecuteModule',
            bridge__pb2.ModuleRequest.SerializeToString,
            bridge__pb2.ModuleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AIAnalyze(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/x404x.v1.BridgeService/AIAnalyze',
            bridge__pb2.AIAnalyzeRequest.SerializeToString,
            bridge__pb2.AIAnalyzeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReconStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/x404x.v1.BridgeService/ReconStream',
            bridge__pb2.ReconRequest.SerializeToString,
            bridge__pb2.ReconResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/x404x.v1.BridgeService/HealthCheck',
            bridge__pb2.HealthCheckRequest.SerializeToString,
            bridge__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
