plugins {
    id 'com.android.application' version '8.2.0'
    id 'com.google.protobuf' version '0.9.4'
}
android {
    namespace 'com.x404x.agent'
    compileSdk 34
    defaultConfig {
        applicationId "com.x404x.agent"
        minSdk 26; targetSdk 34; versionCode 1; versionName "3.2"
    }
}
dependencies {
    implementation 'io.grpc:grpc-okhttp:1.64.0'
    implementation 'io.grpc:grpc-protobuf-lite:1.64.0'
    implementation 'javax.annotation:javax.annotation-api:1.3.2'
}
